//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abuhamza.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int invoice_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> totalQty { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<decimal> AmountTendered { get; set; }
        public Nullable<decimal> change { get; set; }
        public Nullable<int> user_id { get; set; }
        public string voucherNo { get; set; }
        public Nullable<decimal> subTotal { get; set; }
        public Nullable<int> cus_id { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
