//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abuhamza.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int pro_id { get; set; }
        public string barcode { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> sell_price { get; set; }
        public Nullable<long> quantity { get; set; }
        public Nullable<int> fsubCat_id { get; set; }
        public Nullable<int> subCat_id { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> mainCat_id { get; set; }
    }
}
