//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abuhamza.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdvance
    {
        public int advance_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> cus_id { get; set; }
        public string barcode { get; set; }
        public string cus_No { get; set; }
        public string description { get; set; }
        public string cus_Name { get; set; }
        public string voucherNo { get; set; }
    }
}
