//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abuhamza.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetailOrder
    {
        public int detailOrder_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> pro_id { get; set; }
        public string barcode { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> purchasePrice { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
    }
}
