//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abuhamza.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetailInvoice
    {
        public int detailInvoice_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public string barcode { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> sellPrice { get; set; }
        public string voucherNo { get; set; }
    }
}
