//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abuhamza.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchaseOrder()
        {
            this.tblDetailOrders = new HashSet<tblDetailOrder>();
        }
    
        public int order_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<int> sup_id { get; set; }
        public string status { get; set; }
        public string voucherNo { get; set; }
        public Nullable<decimal> paidAmount { get; set; }
        public string orderDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetailOrder> tblDetailOrders { get; set; }
    }
}
