//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abuhamza.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplier
    {
        public int sup_id { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public string contact { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
