//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abuhamza.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTransaction()
        {
            this.tblDetailTransactions = new HashSet<tblDetailTransaction>();
        }
    
        public int tra_id { get; set; }
        public string tra_type { get; set; }
        public string voucherNo { get; set; }
        public Nullable<int> acc_id { get; set; }
        public string description { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> totalQty { get; set; }
        public string barcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetailTransaction> tblDetailTransactions { get; set; }
    }
}
